// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RugbyPlayerSystem.API.Data;

#nullable disable

namespace RugbyPlayerSystem.API.Migrations
{
    [DbContext(typeof(RugbyDbContext))]
    [Migration("20230223075433_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RugbyPlayerSystem.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            BirthDate = new DateTime(2000, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 190.0,
                            Name = "Player 1",
                            PlaceOfBirth = "Auckland",
                            TeamName = "Team 1",
                            Weight = 90.0
                        },
                        new
                        {
                            PlayerId = 2,
                            BirthDate = new DateTime(1994, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 180.0,
                            Name = "Player 2",
                            PlaceOfBirth = "Christchurch",
                            TeamName = "Team 2",
                            Weight = 100.0
                        },
                        new
                        {
                            PlayerId = 3,
                            BirthDate = new DateTime(1998, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 185.0,
                            Name = "Player 3",
                            PlaceOfBirth = "Otago",
                            TeamName = "Team 3",
                            Weight = 79.0
                        });
                });

            modelBuilder.Entity("RugbyPlayerSystem.Models.Team", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<string>("Ground")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Name = "Team 1",
                            Coach = "Default",
                            FoundedYear = 1988,
                            Ground = "Default",
                            Region = "Default",
                            UnionName = "Nationl man's Union"
                        },
                        new
                        {
                            Name = "Team 2",
                            Coach = "Default",
                            FoundedYear = 1975,
                            Ground = "Default",
                            Region = "Default",
                            UnionName = "Nationl man's Union"
                        },
                        new
                        {
                            Name = "Team 3",
                            Coach = "Default",
                            FoundedYear = 1963,
                            Ground = "Default",
                            Region = "Default",
                            UnionName = "Nationl man's Union"
                        });
                });

            modelBuilder.Entity("RugbyPlayerSystem.Models.Union", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Unions");

                    b.HasData(
                        new
                        {
                            Name = "Nationl man's Union"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
